#' Cumulative counting seroconversion episodes per individual
#'
#' @description `cg_annotate_exposures_count` returns a cumulative
#'  count of exposures. These exposures can be vaccines, infection
#'  episodes, or seroconversion episodes (a seroconversion episode is
#'  biologically an infection - the difference between the two is
#'  concomittant symptoms, or diagnostic testing).
#'
#' @param cg a chronogram
#' @param episode_number the column containing infection episode
#'  numbers. `cg_annotate_episodes_find()` Default is episode_number.
#' @param N_seroconversion_episode_number the column name for resulting
#'  episode flag. Generated by
#'  `cg_annotate_episodes_find_seroconversion()`. Default is
#'  "N_seroconversion_episode_number".
#' @param dose_number the column name for cumulative doses. Generated by
#'  `cg_annotate_vaccines_count()`. Default is "dose_number".
#' @param exposure_number the column name to return the cumulative
#'  counter. Default is "exposure_number".
#'
#' @return a chronogram, with episode numbers annotated
#' @seealso [chronogram::cg_annotate_episodes_find()]
#' @export
#'
#' @examples
#' library(dplyr)
#' library(ggplot2)
#' 
#' data("built_smallstudy")
#' cg <- built_smallstudy$chronogram
#' 
#' ## add infections to chronogram ##
#' cg <- cg_add_experiment(
#'   cg,
#'   built_smallstudy$infections_to_add
#' )
#' 
#' ## annotate infections ## 
#' cg <- cg_annotate_episodes_find(
#'    cg,
#'    infection_cols = c("LFT", "PCR", "symptoms"),
#'    infection_present = c("pos", "Post", "^severe")
#' )
#'
#' ## annotate vaccines ## 
#' cg <- cg %>% cg_annotate_vaccines_count(
#'  ## the prefix to the dose columns: ##
#'  dose = dose,
#'  ## the output column name: ##
#'  dose_counter = dose_number,
#'  ## the prefix to the date columns: ##
#'  vaccine_date_stem = date_dose,
#'  ## use 14d to 'star' after a dose ##
#'  intermediate_days = 14)
#' 
#' ## annotate exposures ##
#'cg <- cg %>% cg_annotate_exposures_count(
#'  episode_number = episode_number,
#'  dose_number = dose_number,
#'  ## we have not considered episodes of seroconversion
#'  N_seroconversion_episode_number = NULL
#'  )
#'  
#'  ## Visualise
#'  cg %>% ggplot(
#'  aes(x=calendar_date,
#'  y= exposure_number, 
#'  col = elig_study_id)) + geom_line()
#'   
cg_annotate_exposures_count <- function(
    cg,
    episode_number = episode_number,
    N_seroconversion_episode_number = N_seroconversion_episode_number,
    dose_number = dose_number,
    exposure_number = exposure_number) {
  calendar_date <- attributes(cg)$col_calendar_date
  ids_column_name <- attributes(cg)$col_ids

  ## remove the "star" from doses
  vaccine_number <- NULL ## stop visible binding note
  xx <- cg %>%
    dplyr::mutate(vaccine_number = as.numeric(gsub("star", "", {{ dose_number }})))



  y <- xx %>%
    tibble::as_tibble() %>%
    dplyr::group_by(.data[[ids_column_name]]) %>%
    dplyr::arrange({{ calendar_date }}, .by_group = TRUE) %>%
    tidyr::fill({{ episode_number }}, .direction = "down") %>%
    tidyr::fill({{ N_seroconversion_episode_number }}, .direction = "down") %>%
    dplyr::mutate(
      "{{exposure_number}}" := base::rowSums(
        dplyr::across(c(
          {{ episode_number }},
          {{ N_seroconversion_episode_number }},
          vaccine_number
        )),
        na.rm = TRUE
      )
    ) %>%
    dplyr::ungroup()

  y <- y %>%
    dplyr::select(c(
      {{ ids_column_name }}, {{ calendar_date }},
      {{ exposure_number }}
    ))

  cg <- cg %>%
    dplyr::left_join(y, by = c(
      {{ ids_column_name }},
      {{ calendar_date }}
    ))

  return(cg)
}
