#' Build a chronogram, from a chronogram_skeleton and metadata
#'
#' Decorate a chronogram skeleton with metadata to return a
#' chronogram. For most circumstances, `cg_assemble()` is suggested
#' (which calls `chronogram_skeleton()` and `chronogram()`). See
#' assembly vignette.
#' 
#' @param cg_skeleton a cg_skeleton, generated by
#'   [chronogram::chronogram_skeleton()]
#' @param metadata a tibble containing metadata and ID column name
#'   (and IDs) that are present in cg_skeleton
#'
#' @return An object of chronogram class, with metadata spread across
#'  all calendar_dates.
#'
#' @seealso [chronogram::cg_assemble()],
#'   [chronogram::chronogram_skeleton()],
#'   [chronogram::cg_add_experiment()]
#' @export
#'
#' @examples
#' ## a 3-person chronogram_skeleton ##-------------------------------
#' 
#' small_study <- chronogram_skeleton(
#'   col_ids = elig_study_id,
#'   ids = c(1, 2, 3),
#'   start_date = "01012020",
#'   end_date = "10102021",
#'   col_calendar_date = calendar_date
#' )
#'
#' ## A tibble containing some metadata for our 3 individuals ##
#' data(smallstudy)
#' small_study_metadata <- smallstudy$small_study_metadata
#' small_study_metadata
#'
#' ## Make a chronogram ##
#' small_study_chronogram <- chronogram(
#'   small_study,
#'   small_study_metadata
#' )
#'
chronogram <- function(cg_skeleton, metadata) {
  ## retrieve ids column name from cg_skeleton
  ids_column_name <- attributes(cg_skeleton)$col_ids

  ## Check chronogram_skeleton is valid ##
  stopifnot(validate_chronogram_skeleton(cg_skeleton))

  ## Check metadata is valid ##
  check_metadata(
    x = metadata,
    cg_skeleton = cg_skeleton
  )

  ##

  ## stash levels of cg_skeleton::ids ##
  lvls <- cg_skeleton %>%
    dplyr::pull(.data[[{{ ids_column_name }}]])
  lvls <- levels(lvls)

  ## left_join based on ids_column_name
  x <- dplyr::left_join(
    cg_skeleton %>%
      dplyr::mutate({{ ids_column_name }} :=
        as.character(
          .data[[{{ ids_column_name }}]]
        )),
    metadata %>%
      dplyr::mutate({{ ids_column_name }} :=
        as.character(
          .data[[{{ ids_column_name }}]]
        )),
    by = {{ ids_column_name }}
  )

  ## re-apply the levels from cg_skeleton::ids ##
  x <- x %>%
    dplyr::mutate({{ ids_column_name }} :=
      factor(
        .data[[{{ ids_column_name }}]],
        levels = lvls
      ))

  metadata_cols <- colnames(metadata)

  x <- new_chronogram(x, metadata_cols)

  stopifnot(validate_chronogram(x))


  return(x)
}
